name: PortChuuExtras
main: sh.chuu.port.mc.portchuuextras.PortChuuExtras
version: @version@
description: Port Chuu Extra Plugin
api-version: 1.15
author: Simon Chuu
website: https://port.chuu.sh
softdepend: [ProtocolLib]

commands:
  fly:
    aliases: [levitateban]
    description: idk why did i make this
    usage: /fly
    permission: portchuuextras.command.fly
  op:
    aliases: [summontnt]
    description: idk why did i make this
    usage: /op <name>
    permission: portchuuextras.command.op
  xray:
    aliases: [selfban]
    description: idk why did i make this
    usage: /xray
    permission: portchuuextras.command.xray
  # Contributor Commands
  simonorj:
    aliases: [chuu]
    description: idk why did i make this
    usage: /xray
    permission: portchuuextras.command.simonorj

permissions:
  portchuuextras.command.fly:
    default: true
  portchuuextras.command.op:
    default: true
  portchuuextras.command.xray:
    default: true
  # Contributor Commands
  portchuuextras.command.simonorj:
    default: true
  # Listener Commands
  portchuuextras.interact.sit:
    default: true
